
> socket-api@1.0.0 nodemon /Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api
> nodemon index-socket-api

[33m[nodemon] 1.19.1[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching: *.*[39m
[32m[nodemon] starting `node index-socket-api.js`[39m
      _                     _ 
   __| | ___  ___ _ __  ___| |_ _ __ ___  __ _ _ __ ____ 
  / _` |/ _ \/ _ \ '_ \/ __| __| '__/ _ \/ _` | '_ ` _  \
 | (_| |  __/  __/ |_) \__ \ |_| | |  __/ (_| | | | | | |
  \__,_|\___|\___| .__/|___/\__|_|  \___|\__,_|_| |_| |_|
                 |_|
 =====================   starting   =====================
INFO | State transition (start): Stopped -> LoggerInit
INFO | logger ready: std out/err
Example app listening on port 4000!
INFO | State transition (logger-started): LoggerInit -> PluginInit
INFO | deepstream version: 3.2.4
INFO | storage ready: no storage connector specified
INFO | cache ready: local cache
INFO | authenticationHandler ready: none
INFO | permissionHandler ready: none
INFO | State transition (plugins-started): PluginInit -> ServiceInit
INFO | State transition (services-started): ServiceInit -> ConnectionEndpointInit
INFO | Listening for websocket connections on 0.0.0.0:6020/deepstream
INFO | Listening for health checks on path /health-check 
INFO | connectionEndpoint ready: ÂµWebSocket Connection Endpoint
INFO | Listening for http connections on 0.0.0.0:8080
INFO | Listening for health checks on path /health-check 
INFO | connectionEndpoint ready: HTTP connection endpoint
INFO | State transition (connection-endpoints-started): ConnectionEndpointInit -> Running
INFO | Deepstream started
Websocket error event:  connectionError
INCOMING_CONNECTION | from  (127.0.0.1)
AUTH_ATTEMPT | 127.0.0.1: AREQ{}
AUTH_SUCCESSFUL | open
Websocket Login Success!
connection error: { MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo mongo:27017]
    at Pool.<anonymous> (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/topologies/server.js:431:11)
    at Pool.emit (events.js:198:13)
    at connect (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/pool.js:557:14)
    at makeConnection (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/connect.js:39:11)
    at callback (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/connect.js:261:5)
    at Socket.err (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/connect.js:286:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at Promise.resolve.then (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/uWebSockets.js/uws.js:24:5)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
(node:1083) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo mongo:27017]
    at Pool.<anonymous> (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/topologies/server.js:431:11)
    at Pool.emit (events.js:198:13)
    at connect (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/pool.js:557:14)
    at makeConnection (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/connect.js:39:11)
    at callback (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/connect.js:261:5)
    at Socket.err (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/connect.js:286:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at Promise.resolve.then (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/uWebSockets.js/uws.js:24:5)
(node:1083) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1083) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
INCOMING_CONNECTION | from  (127.0.0.1)
AUTH_ATTEMPT | 127.0.0.1: AREQ{}
AUTH_SUCCESSFUL | open
npm ERR! code ELIFECYCLE
npm ERR! errno 143
npm ERR! socket-api@1.0.0 nodemon: `nodemon index-socket-api`
npm ERR! Exit status 143
npm ERR! 
npm ERR! Failed at the socket-api@1.0.0 nodemon script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vladimirgrujin/.npm/_logs/2019-07-24T06_10_18_709Z-debug.log

> socket-api@1.0.0 nodemon /Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api
> nodemon index-socket-api

[33m[nodemon] 1.19.1[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching: *.*[39m
[32m[nodemon] starting `node index-socket-api.js`[39m
      _                     _ 
   __| | ___  ___ _ __  ___| |_ _ __ ___  __ _ _ __ ____ 
  / _` |/ _ \/ _ \ '_ \/ __| __| '__/ _ \/ _` | '_ ` _  \
 | (_| |  __/  __/ |_) \__ \ |_| | |  __/ (_| | | | | | |
  \__,_|\___|\___| .__/|___/\__|_|  \___|\__,_|_| |_| |_|
                 |_|
 =====================   starting   =====================
INFO | State transition (start): Stopped -> LoggerInit
INFO | logger ready: std out/err
Example app listening on port 4000!
INFO | State transition (logger-started): LoggerInit -> PluginInit
INFO | deepstream version: 3.2.4
INFO | storage ready: no storage connector specified
INFO | cache ready: local cache
INFO | authenticationHandler ready: none
INFO | permissionHandler ready: none
INFO | State transition (plugins-started): PluginInit -> ServiceInit
INFO | State transition (services-started): ServiceInit -> ConnectionEndpointInit
INFO | Listening for websocket connections on 0.0.0.0:6020/deepstream
INFO | Listening for health checks on path /health-check 
INFO | connectionEndpoint ready: ÂµWebSocket Connection Endpoint
INFO | Listening for http connections on 0.0.0.0:8080
INFO | Listening for health checks on path /health-check 
INFO | connectionEndpoint ready: HTTP connection endpoint
INFO | State transition (connection-endpoints-started): ConnectionEndpointInit -> Running
INFO | Deepstream started
Websocket error event:  connectionError
connection error: { MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo mongo:27017]
    at Pool.<anonymous> (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/topologies/server.js:431:11)
    at Pool.emit (events.js:198:13)
    at connect (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/pool.js:557:14)
    at makeConnection (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/connect.js:39:11)
    at callback (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/connect.js:261:5)
    at Socket.err (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/connect.js:286:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at Promise.resolve.then (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/uWebSockets.js/uws.js:24:5)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
(node:1251) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo mongo:27017]
    at Pool.<anonymous> (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/topologies/server.js:431:11)
    at Pool.emit (events.js:198:13)
    at connect (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/pool.js:557:14)
    at makeConnection (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/connect.js:39:11)
    at callback (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/connect.js:261:5)
    at Socket.err (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/mongodb-core/lib/connection/connect.js:286:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at Promise.resolve.then (/Users/vladimirgrujin/Code/MY-PROJECTS/company-project/socket-api/node_modules/uWebSockets.js/uws.js:24:5)
(node:1251) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1251) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
INCOMING_CONNECTION | from  (127.0.0.1)
AUTH_ATTEMPT | 127.0.0.1: AREQ{}
AUTH_SUCCESSFUL | open
Websocket Login Success!
INCOMING_CONNECTION | from  (127.0.0.1)
AUTH_ATTEMPT | 127.0.0.1: AREQ{}
AUTH_SUCCESSFUL | open
CLIENT_DISCONNECTED | open
INCOMING_CONNECTION | from  (127.0.0.1)
AUTH_ATTEMPT | 127.0.0.1: AREQ{}
AUTH_SUCCESSFUL | open
NOT_SUBSCRIBED | open is not subscribed to undefined-1-1
NOT_SUBSCRIBED | open is not subscribed to undefined
Websocket error event:  NOT_SUBSCRIBED
CLIENT_DISCONNECTED | open
INCOMING_CONNECTION | from  (127.0.0.1)
AUTH_ATTEMPT | 127.0.0.1: AREQ{}
AUTH_SUCCESSFUL | open
CLIENT_DISCONNECTED | open
INCOMING_CONNECTION | from  (127.0.0.1)
AUTH_ATTEMPT | 127.0.0.1: AREQ{}
AUTH_SUCCESSFUL | open
CLIENT_DISCONNECTED | open
INCOMING_CONNECTION | from  (127.0.0.1)
AUTH_ATTEMPT | 127.0.0.1: AREQ{}
AUTH_SUCCESSFUL | open
CLIENT_DISCONNECTED | open
npm ERR! code ELIFECYCLE
npm ERR! errno 143
npm ERR! socket-api@1.0.0 nodemon: `nodemon index-socket-api`
npm ERR! Exit status 143
npm ERR! 
npm ERR! Failed at the socket-api@1.0.0 nodemon script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vladimirgrujin/.npm/_logs/2019-07-24T06_12_27_184Z-debug.log
